SELECT
    ANIMAL_ID,
    ANIMAL_INS.ANIMAL_TYPE,
    ANIMAL_INS.NAME
FROM 
    ANIMAL_INS
JOIN 
    ANIMAL_OUTS
USING 
    (ANIMAL_ID)
WHERE
    LOWER(ANIMAL_INS.SEX_UPON_INTAKE) LIKE '%intact%'
AND (
    LOWER(ANIMAL_OUTS.SEX_UPON_OUTCOME) LIKE '%spayed%'
    OR LOWER(ANIMAL_OUTS.SEX_UPON_OUTCOME) LIKE '%neutered%'
)
ORDER BY 
    ANIMAL_ID, 
    ANIMAL_TYPE, 
    NAME
