WITH MOST_REVIEWER AS (
    SELECT
        MEMBER_ID,
        COUNT(REVIEW_ID),
        DENSE_RANK() OVER(ORDER BY COUNT(REVIEW_ID) DESC) AS RANKING
    FROM
        MEMBER_PROFILE
    JOIN
        REST_REVIEW
    USING
        (MEMBER_ID)
    GROUP BY
        MEMBER_ID 
)
SELECT
    MEMBER_NAME,
    REVIEW_TEXT,
    DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM
    MEMBER_PROFILE
JOIN
    REST_REVIEW
USING
    (MEMBER_ID)
JOIN
    MOST_REVIEWER
USING
    (MEMBER_ID)
WHERE
    RANKING = 1
ORDER BY
    REVIEW_DATE,
    REVIEW_TEXT